---
 - name: configuring tomcat10 on all servers
   hosts: all
   tasks: 
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
        update_cache: yes
    - name: copy customised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change the port 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart the tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: pause for 1 minute
      pause:
        minutes: 1
    - name: check tomcat on server1
      uri:
        url: http://172.31.8.104:9090
        status_code: 200
    - name: check tomcat on server2
      uri:
        url: http://172.31.6.200:9090
        status_code: 200
...

          

