---
 - name: delete the file if the file is empty file
   hosts: all
   tasks:
     - name: check the file 
       stat:
         path: /tmp/file456
       register: a
     - name: display the output of the above module
       debug:
         var: a
     - name: delete the file if the file is empty
       file:
         name: /tmp/file456
         state: absent
       when: a.stat.size == 0
...



