---
 - name: implementing host scope variables
   hosts: webserver
   tasks:
     - name: git installation
       apt:
         name: "{{a}}"
         state: "{{b}}"
         update_cache: "{{c}}"
...

