---
- name: create an empty folder and download the jenkins.war into it
  hosts: all
  tasks:
    - name: create an empty folder
      file:
         name: /tmp/jenkins
         state: directory
    - name: download teh jenkins.war into it
      get_url: 
         url:  https://get.jenkins.io/war-stable/2.479.1/jenkins.war
         dest: /tmp/jenkins
...


