---
 - name: install and uninstall s/w
   hosts: all 
   vars: 
     - a : git
     - b : absent
     - c : no
   tasks: 
     - name: uninstall git
       apt:
           name: "{{a}}"
           state: "{{b}}"
           update_cache: "{{c}}"
...

