---
 - name: configuring apache2
   hosts: all
   tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit the index.html file
      copy:
        content: "hi how are you! "
        dest: /var/www/html/index.html
    - name: restart the apache
      service:
        name: apache2
        state: restarted
    - name: check the configuration of server1
      uri:
        url: http://172.31.8.104
        status_code: 200
    - name: check the configuration of server2
      uri:
        url: http://172.31.6.200
        status_code: 200
...


