---
 - name: tomcat10 installation
   hosts: all
   tasks: 
     - name: installing tomcat10
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: tomcat10,b: present,c: yes}
         - {a: tomcat10-admin,b: present,c: no}
     - name: copy xml file
       copy: 
         src: tomcat-users.xml
         dest: /etc/tomcat10
     - name: change port number
       replace:
         regexp: 8080
         replace: 9999
         path: /etc/tomcat10/server.xml
     - name: restarting service
       service:
         name: tomcat10
         state: restarted
     - name: pausing servers
       pause:
         seconds: 40
     - name: checking the status
       uri:
         url: "{{item}}"
         status_code: 200
       with_items: 
         - http://172.31.8.104
         - http://172.31.6.200

             
