---
 - name: delete file  if the file is executable
   hosts: all
   tasks: 
     - name: capture info about the file
       stat:
         path: /tmp/file123
       register: b
     - name: display the output of the above module
       debug: 
         var: b
     - name: delete the file if the file is exucutable
       file:
         name: /tmp/file123
         state: absent
       when: b.stat.executable == true
...

