---
 - name: install and uninstall s/w applications 
   hosts: all
   tasks: 
     - name: install and uninstall s/w
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: git,b: present,c: yes}
         - {a: maven,b: present,c: yes}
         - {a: tree,b: absent,c: no}
...


