---
 - name: implementing host scope variables
   hosts: 172.31.8.104
   tasks:
     - name: create user
       user:
         name: "{{a}}"
         password: "{{b}}"
         uid: "{{c}}"
         home: "{{d}}"
         shell: "{{e}}"
         comment: "{{f}}"
...

