---
 - name: install s/w for jenkins ci-cd 
   hosts: localhost
   become: yes   
   tasks: 
     - name: install different s/w
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: openjdk-17-jdk,b: present,c: yes}
         - {a: git,b: present,c: no}
         - {a: maven,b: present,c: no}
     - name: install jenkins
       get_url: 
         url: https://get.jenkins.io/war-stable/2.479.2/jenkins.war
         dest: /home/ubuntu/
 - name: install tomcat10 and require s/w's
   hosts: combined
   become: yes
   tasks:  
      - name: install tomacat10
        apt: 
           name: "{{item.a}}"
           state: "{{item.b}}"
           update_cache: "{{item.c}}"
        with_items:
           - {a: tomcat10,b: present,c: yes}
           - {a: tomcat10-admin,b: present,c: no}
      - name: edit the tomcat-users.xml file
        copy:
           src: tomcat-users.xml
           dest: /etc/tomcat10
        notify: restart the tomcat10
      - name: check url response
        uri:
           url: "{{item}}"
           status_code: 200
        with_items:
           - http://172.31.8.104
           - http://172.31.6.200    
   handlers: 
      - name: restart the tomcat10
        service:
           name: tomcat10
           state: restarted

                
           
