---
 - name: error handling
   hosts: all
   tasks:
     - block:
         - name: install git
           apt:
             name: git
             state: present
             update_cache: yes
       rescue:
         - name: install git
           yum:
             name: git
             state: present
             update_cache: yes
       always:
         - name: configuring maven using github url
           git:
             repo: https://github.com/IntelliqDevops/newmaven.git
             dest: /tmp/maven
         - name: get logs
           debug:
             msg: "git installation is success"

...

                     

